name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # updates every 12 hours
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}
