name: Update GitHub Score

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:        

permissions:
  contents: write          

jobs:
  update-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Run GitHub Score script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ pass token
        run: python score.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes to commit" || (
            git commit -m "🔄 Updated GitHub Score"
            git push origin HEAD:${{ github.ref_name }}
          )
